global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerting_rules.yml 
  - /etc/prometheus/recording_rules.yml 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["prometheus:9090"]

  # - job_name: "spring-actuator"
  #   metrics_path: "/actuator/prometheus"
  #   scrape_interval: 5s
  #   static_configs:
  #   - targets: ["HOST_IP:8080"]

  - job_name: "node" 
    static_configs: 
    - targets: ["node-exporter:9100"]

  - job_name: "cadvisor" 
    scrape_interval: 5s 
    static_configs: 
    - targets: ["cadvisor:8080"]  