global:
  scrape_interval: 1m
scrape_configs:
- job_name: "prometheus"
  scrape_interval: 1m
  static_configs:
  - targets: ["172.25.0.4:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["172.25.0.3:9100"]