global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerting_rules.yml 
  - /etc/prometheus/recording_rules.yml 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          group: "node-exporter"
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*:9100"
        action: drop

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]  